name: Java CI with Maven
on: [push, pull_request]
jobs:
  build:
    name: "Maven Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 11
          cache: "maven"
      - name: "Build with Maven"
        run: mvn verify -B -U
